name: mlos_python_environment
channels:
  - defaults
dependencies:
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - numpy=1.18.1
  - pandas=1.0.3
  - pylint=2.3.1
  - pyodbc=4.0.30
  - pip
  - jupyterlab
  - jupyter
  - ipykernel
  - matplotlib
  - seaborn
  - python
  - pip:
    - grpcio-tools==1.30.0
    - bayesian-optimization==1.0.1
    - tensorboardX==2.1
